### ISSUE TITLE
Support empty subgraph names

### ISSUE THREAD

**Issue by punkeel** [excalidraw/mermaid-to-excalidraw#24]
Example test case:

```
flowchart
    subgraph B[ ]
    V1(Visitor 1)-.->Hey[Server]
    end
```

```mermaid
flowchart
    subgraph B[ ]
    V1(Visitor 1)-.->Hey[Server]
    end
```

Today, this causes console errors:
```console
react-dom.development.js:4299 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at isTransparent (utils.ts:603:34)
    at isElementDraggableFromInside (collision.ts:60:19)
    at isHittingElementNotConsideringBoundingBox (collision.ts:155:7)
    at hitTest (collision.ts:103:10)
    at eval (App.tsx:3090:14)
    at eval (comparisons.ts:67:40)
    at Array.filter (<anonymous>)
    at getElementsAtPosition (comparisons.ts:66:19)
    at App.getElementsAtPosition (App.tsx:3089:33)
    at App.getElementAtPosition (App.tsx:3037:33)
```

**Comment by ad1992** [comment]
@punkeel I just tried this test case in [playground](https://mermaid-to-excalidraw.vercel.app/) and its working well
<img width="1149" alt="Screenshot 2023-09-20 at 6 18 01 PM" src="https://github.com/excalidraw/mermaid-to-excalidraw/assets/11256141/94636e6b-fbf1-4d56-bf9a-4421455ee494">

where are you seeing this error ?

**Comment by punkeel** [comment]
The error occured on https://mermaid-to-excalidraw.vercel.app/

I can confirm this is working now 👍  - thanks!
